# Generated by Django 5.1.3 on 2025-09-11 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('tutor', '0002_course_alter_classtiming_id_alter_syllabus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor.course'),
        ),
    ]
